# Generated by Django 2.0.7 on 2018-10-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_key', models.CharField(max_length=300)),
                ('product_name', models.CharField(max_length=300)),
            ],
        ),
    ]
